baseURL = "https://max-dev.blog/"
languageCode = "en-us"
title = "My Personal Blog"
theme = "terminal"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false

[params]
  contentTypeName = "posts"
  themeColor = "dark"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  readMore = "Read more"

  [params.logo]
    logoText = "My Terminal"
    logoHomeLink = "/"

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "LeetCode"
  url = "/leetcode"
  weight = 2

[[menu.main]]
  name = "Courses"
  url = "/courses"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
