baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Personal Blog"
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "dark"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  readMore = "Read more"

  [params.logo]
    logoText = "My Terminal"
    logoHomeLink = "/"

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
